/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFACES;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author MEDAC
 */
public class E_2_parecidosPractica extends javax.swing.JFrame {

    int contadorIntentos;
    int numeroMaqunaAleatorio;

    /**
     * Creates new form E_2_parecidosPractica
     */
    public E_2_parecidosPractica() {
        initComponents();
        contadorIntentos = 0;
        
        //System.out.println("El numero de la maquina para no tardar es : " + numeroMaqunaAleatorio);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        tituloAdivinaNumero = new javax.swing.JLabel();
        tituloInfo = new javax.swing.JLabel();
        tituloApuesta = new javax.swing.JLabel();
        textoApuesta = new javax.swing.JTextField();
        botonApostar = new javax.swing.JButton();
        textoIntentos = new javax.swing.JTextField();
        tituloIntentos = new javax.swing.JLabel();
        botonRendirse = new javax.swing.JButton();
        tituloMensaje = new javax.swing.JLabel();
        textMensaje = new javax.swing.JTextField();
        botonEmpezar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloAdivinaNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloAdivinaNumero.setText("ADIVINA EL NUMERO");

        tituloInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloInfo.setText("El objetivo es encontrar el numero entre 1 y el 100 que ha pensado el ordenador");

        tituloApuesta.setText("TU APUESTA");

        textoApuesta.setEditable(false);

        botonApostar.setText("APOSTAR");
        botonApostar.setEnabled(false);
        botonApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonApostarActionPerformed(evt);
            }
        });

        textoIntentos.setEditable(false);

        tituloIntentos.setText("INTENTOS");

        botonRendirse.setText("RENDIRSE");
        botonRendirse.setEnabled(false);
        botonRendirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRendirseActionPerformed(evt);
            }
        });

        tituloMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloMensaje.setText("MENSAJES");

        textMensaje.setEditable(false);

        botonEmpezar.setText("EMPEZAR");
        botonEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmpezarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fondoLayout.createSequentialGroup()
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloMensaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(fondoLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tituloApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tituloIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textoIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(58, 58, 58)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botonApostar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonRendirse, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(tituloAdivinaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEmpezar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tituloAdivinaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonApostar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonRendirse, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textoIntentos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addComponent(tituloIntentos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(13, 13, 13)
                .addComponent(tituloMensaje)
                .addGap(18, 18, 18)
                .addComponent(textMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEmpezar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmpezarActionPerformed
        //cuando le doy al boton se habilitan los campos
        botonApostar.setEnabled(true);
        botonRendirse.setEnabled(true);
        textMensaje.setEditable(true);
        textoApuesta.setEditable(true);

        //borro el texto de mensaje
        textMensaje.setText("");
        textoApuesta.setText("");
        textoIntentos.setText("");

    }//GEN-LAST:event_botonEmpezarActionPerformed

    private void botonApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonApostarActionPerformed
        try {
            int numeroJugador = Integer.parseInt(textoApuesta.getText());
            if (numeroJugador >= 1 && numeroJugador <= 100) {
                numeroMaqunaAleatorio = (int) (Math.random() * (100 - 1 + 1) + 1);

                if (numeroJugador > numeroMaqunaAleatorio) {
                    textMensaje.setText("INTENTALO CON UN NUMERO MAS CHIQUITO");
                    contadorIntentos++;
                    textoIntentos.setText(String.valueOf(contadorIntentos));
                } else if (numeroJugador < numeroMaqunaAleatorio) {
                    textMensaje.setText("INTENTALO CON UN NUMERO MAS GRANDE CASI LO TIENES");
                    contadorIntentos++;
                    textoIntentos.setText(String.valueOf(contadorIntentos));
                } else {
                    textMensaje.setText("El numero en el que pensaba la maquina era -> " + numeroMaqunaAleatorio);
                }
            }else{
                   JOptionPane.showMessageDialog(this, "El dato que intentas introducir no esta en los rangos indicados",
                    "cosas de informacion", JOptionPane.ERROR_MESSAGE);      
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El dato introducido no es correcto",
                    "cosas de informacion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonApostarActionPerformed

    private void botonRendirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRendirseActionPerformed
        textMensaje.setText("TE HAS RENDIDO QUE POCA TOLERANCIA A LA FRUSTRACION" + numeroMaqunaAleatorio);
        botonApostar.setEnabled(false);
        textMensaje.setEditable(false);
        textoApuesta.setEditable(false);
    }//GEN-LAST:event_botonRendirseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(E_2_parecidosPractica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(E_2_parecidosPractica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(E_2_parecidosPractica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(E_2_parecidosPractica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E_2_parecidosPractica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonApostar;
    private javax.swing.JButton botonEmpezar;
    private javax.swing.JButton botonRendirse;
    private javax.swing.JPanel fondo;
    private javax.swing.JTextField textMensaje;
    private javax.swing.JTextField textoApuesta;
    private javax.swing.JTextField textoIntentos;
    private javax.swing.JLabel tituloAdivinaNumero;
    private javax.swing.JLabel tituloApuesta;
    private javax.swing.JLabel tituloInfo;
    private javax.swing.JLabel tituloIntentos;
    private javax.swing.JLabel tituloMensaje;
    // End of variables declaration//GEN-END:variables
}
