/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFACES;

/**
 *
 * @author enyag
 */
public class E_interfaces_141 extends javax.swing.JFrame {

    /**
     * Creates new form E_interfaces_141
     */
    public E_interfaces_141() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadio = new javax.swing.ButtonGroup();
        fondo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        textG = new javax.swing.JTextField();
        valorF = new javax.swing.JLabel();
        textF = new javax.swing.JTextField();
        valorG = new javax.swing.JLabel();
        boton3 = new javax.swing.JButton();
        convertirC = new javax.swing.JRadioButton();
        convertirF = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(204, 255, 204));

        titulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 51, 51));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Temperaturas");
        titulo.setToolTipText("");

        textG.setText("Cº: ");

        textF.setText("Fº:");

        boton3.setBackground(new java.awt.Color(0, 102, 102));
        boton3.setText("Boton3");
        boton3.setActionCommand("");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        grupoRadio.add(convertirC);
        convertirC.setText("Cº");

        grupoRadio.add(convertirF);
        convertirF.setText("Fº");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(valorF, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(textG, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(convertirC)
                        .addGap(37, 37, 37)
                        .addComponent(convertirF)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(valorG, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textF))))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(titulo)))
                .addContainerGap())
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(boton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convertirC)
                    .addComponent(textG, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertirF))
                .addGap(51, 51, 51)
                .addComponent(valorG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorF)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//TODA LA FUNCIONALIDAD EN UN BOTON
    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        try {
            //Funcionalidad de C a F
            //( °C × 9 / 5) + 32 =  °F
            final double F = 32;

            if (convertirC.isSelected()) {
                String textoGrados = textG.getText();
                double grados = Double.parseDouble(textoGrados.substring(textoGrados.indexOf(":") + 1));//guardo el valor de gardos que quiero convertir
                double conversionF = (grados * 9 / 5) + F;
                valorF.setText(conversionF + "ºF");

            } else if (convertirF.isSelected()) {
                //Funcionalidad de F a C
                //(32 °F − 32) × 5 / 9 = 0 °C
                String textoF = textF.getText();
                double f = Double.parseDouble(textoF.substring(textoF.indexOf(":") + 1));
                double conversionC = (f - F) * 5 / 9;
                valorG.setText(conversionC + "ºC");
            }

        } catch (NumberFormatException e) {
            textG.setText("Elemento vacio");
            textF.setText("Elemento vacio");

        }


    }//GEN-LAST:event_boton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(E_interfaces_141.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(E_interfaces_141.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(E_interfaces_141.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(E_interfaces_141.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E_interfaces_141().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton3;
    private javax.swing.JRadioButton convertirC;
    private javax.swing.JRadioButton convertirF;
    private javax.swing.JPanel fondo;
    private javax.swing.ButtonGroup grupoRadio;
    private javax.swing.JTextField textF;
    private javax.swing.JTextField textG;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel valorF;
    private javax.swing.JLabel valorG;
    // End of variables declaration//GEN-END:variables
}
