/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFACES;

import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author enyag
 */
public class E_interfaces_143 extends javax.swing.JFrame {

    /**
     * Creates new form E_interfaces_143
     */
    public E_interfaces_143() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        marcas = new javax.swing.JLabel();
        conponentes = new javax.swing.JLabel();
        listaMarcas = new javax.swing.JComboBox<>();
        listaComponentes = new javax.swing.JComboBox<>();
        boton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo1.setBackground(new java.awt.Color(255, 204, 255));
        fondo1.setToolTipText("");

        titulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(51, 0, 51));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Ejercicio 143");

        marcas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        marcas.setForeground(new java.awt.Color(51, 0, 51));
        marcas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marcas.setText("Marcas");

        conponentes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        conponentes.setForeground(new java.awt.Color(51, 0, 51));
        conponentes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conponentes.setText("Componentes");

        listaMarcas.setBackground(new java.awt.Color(204, 204, 204));
        listaMarcas.setForeground(new java.awt.Color(255, 204, 255));
        listaMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione una marca", "AMD", "Intel", "NVIDIA" }));
        listaMarcas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaMarcasItemStateChanged(evt);
            }
        });

        listaComponentes.setBackground(new java.awt.Color(204, 204, 204));
        listaComponentes.setForeground(new java.awt.Color(255, 204, 255));

        boton.setBackground(new java.awt.Color(0, 0, 0));
        boton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton.setForeground(new java.awt.Color(255, 204, 255));
        boton.setText("PULSAR");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondo1Layout = new javax.swing.GroupLayout(fondo1);
        fondo1.setLayout(fondo1Layout);
        fondo1Layout.setHorizontalGroup(
            fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondo1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondo1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(marcas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaComponentes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conponentes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
            .addGroup(fondo1Layout.createSequentialGroup()
                .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondo1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondo1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(boton)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        fondo1Layout.setVerticalGroup(
            fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondo1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(titulo)
                .addGap(37, 37, 37)
                .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcas)
                    .addComponent(conponentes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(boton)
                .addGap(102, 102, 102))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fondo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //CADA VEZ QUE PULSO EL BOTON SE REALIZA UNA ACCION
    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        if (listaMarcas.getSelectedIndex() != 0) {//si la posicion es diferente a 0
            String ruta = "gatobien.jpg";
            ImageIcon icono = new ImageIcon(getClass().getResource(ruta));
            JOptionPane.showMessageDialog(this, "Ha selecionado un elemento",
                    "GatoBienComponentes", JOptionPane.INFORMATION_MESSAGE, icono);
     

        } else {
            String ruta = "gatomal.jpg";
            ImageIcon icono = new ImageIcon(getClass().getResource(ruta));
            JOptionPane.showMessageDialog(this, "Debes de seleccionar un elemento",
                    "GatoMalComponentes", JOptionPane.INFORMATION_MESSAGE, icono);
        }

    }//GEN-LAST:event_botonActionPerformed

    private void listaMarcasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaMarcasItemStateChanged
        //Variables globales donde guardo una lista de datos de cada marca
        String datosIntel[] = {"HD 3000", "HD 4000", "IRIS 600"};
        String datosAMD[] = {"RX Serie 500", "Vega Series", "RX Series 6000"};
        String datosNvidia[] = {"GTX Serie 1000", "GTX Serie 2000", "GTX Serie 3000"};
        String datosVacio[] = {" "};

        HashMap<String, String[]> diccionarioMarcas = new HashMap<String, String[]>();
        diccionarioMarcas.put("Intel", datosIntel);
        diccionarioMarcas.put("AMD", datosAMD);
        diccionarioMarcas.put("NVIDIA", datosNvidia);
        diccionarioMarcas.put("Selecione una marca", datosVacio);

        String keyMarca = "";
        keyMarca = listaMarcas.getSelectedItem().toString();//seleciono los elementos dentoro de la lista 
        String[] componentes = diccionarioMarcas.get(keyMarca);//valores de la listaMarcas
        listaComponentes.removeAllItems();//limpiar combobox

        for (String componente : componentes) {
            listaComponentes.addItem(componente);
        }


    }//GEN-LAST:event_listaMarcasItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(E_interfaces_143.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(E_interfaces_143.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(E_interfaces_143.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(E_interfaces_143.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E_interfaces_143().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JLabel conponentes;
    private javax.swing.JPanel fondo1;
    private javax.swing.JComboBox<String> listaComponentes;
    private javax.swing.JComboBox<String> listaMarcas;
    private javax.swing.JLabel marcas;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
