/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFACES;

import javax.swing.JOptionPane;

/**
 *
 * @author MEDAC
 */
public class Juego_145 extends javax.swing.JFrame {

    /**
     * Creates new form Juego_145
     */
    public Juego_145() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        fondo1 = new javax.swing.JPanel();
        titulo1 = new javax.swing.JLabel();
        datosJugador = new javax.swing.JTextField();
        botonJugar = new javax.swing.JButton();
        elecion = new javax.swing.JLabel();
        radiuxPares = new javax.swing.JRadioButton();
        radiuxNones = new javax.swing.JRadioButton();
        informacion = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo1.setBackground(new java.awt.Color(204, 255, 255));

        titulo1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        titulo1.setForeground(new java.awt.Color(0, 0, 51));
        titulo1.setText("Juego Pares y Nones");

        datosJugador.setBackground(new java.awt.Color(0, 204, 204));

        botonJugar.setBackground(new java.awt.Color(0, 204, 204));
        botonJugar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        botonJugar.setForeground(new java.awt.Color(255, 255, 255));
        botonJugar.setText("JUGAR");
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });

        elecion.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        elecion.setForeground(new java.awt.Color(0, 0, 51));
        elecion.setText("Elige");

        buttonGroup1.add(radiuxPares);
        radiuxPares.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radiuxPares.setForeground(new java.awt.Color(0, 0, 51));
        radiuxPares.setText("PARES");

        buttonGroup1.add(radiuxNones);
        radiuxNones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radiuxNones.setForeground(new java.awt.Color(0, 0, 51));
        radiuxNones.setText("NONES");

        informacion.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        informacion.setForeground(new java.awt.Color(0, 0, 51));
        informacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        informacion.setText("ELIGE UN NUMERO DEL 1 AL 5");

        botonSalir.setBackground(new java.awt.Color(204, 204, 255));
        botonSalir.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("<<ADIOS>>");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondo1Layout = new javax.swing.GroupLayout(fondo1);
        fondo1.setLayout(fondo1Layout);
        fondo1Layout.setHorizontalGroup(
            fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondo1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondo1Layout.createSequentialGroup()
                        .addComponent(titulo1)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondo1Layout.createSequentialGroup()
                        .addComponent(botonJugar)
                        .addGap(125, 125, 125))))
            .addGroup(fondo1Layout.createSequentialGroup()
                .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondo1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(elecion)
                            .addGroup(fondo1Layout.createSequentialGroup()
                                .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radiuxNones)
                                    .addComponent(radiuxPares))
                                .addGap(32, 32, 32)
                                .addComponent(informacion))))
                    .addGroup(fondo1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(botonSalir)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondo1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(datosJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        fondo1Layout.setVerticalGroup(
            fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(elecion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiuxPares)
                .addGroup(fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondo1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(radiuxNones))
                    .addGroup(fondo1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(datosJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonJugar)
                .addGap(42, 42, 42)
                .addComponent(botonSalir)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //BOTON PARA PODER JUGAR
    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed

        //obtengo los datos que necesite
        int jugador = Integer.parseInt(datosJugador.getText());
        int sumaRes = 0;
        String ganadorFinal = "";
        Info_145 resGanador;
        
        if (jugador >= 1 && jugador <= 5) {
            int maquinaAle = (int) (Math.random() * (5 - 1 + 1) + 1);
            sumaRes = jugador + maquinaAle;
           
            
            
            
            if (radiuxPares.isSelected()) {
                if (sumaRes%2==0) {
                    
                    ganadorFinal = "Jugador";
                }else{
                    ganadorFinal = "Maquina";
                }
                 resGanador = new Info_145(jugador, maquinaAle,sumaRes,ganadorFinal);
                 resGanador.setVisible(true);
            }
            else{
                
            }
        }else{
            JOptionPane.showMessageDialog(this, "El dato introducido no es correcto",
                    "cosas de informacion", JOptionPane.ERROR_MESSAGE);
        
        } 
        //Ocultamos esta ventana la principal
        //Para que en el momento que aparezca la otra esta desaparezca
        this.setVisible(false);
    }//GEN-LAST:event_botonJugarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0); //para salir completamente
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego_145.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego_145.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego_145.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego_145.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego_145().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonJugar;
    private javax.swing.JButton botonSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField datosJugador;
    private javax.swing.JLabel elecion;
    private javax.swing.JPanel fondo1;
    private javax.swing.JLabel informacion;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JRadioButton radiuxNones;
    private javax.swing.JRadioButton radiuxPares;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
}
